# Generated by Django 4.2.10 on 2024-02-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloths',
            name='MRP',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
