# Generated by Django 4.2.10 on 2024-02-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_alter_cloths_mrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoldItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=256)),
                ('Seller', models.CharField(max_length=256)),
                ('Code', models.CharField(max_length=5)),
                ('Price', models.IntegerField()),
                ('MRP', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date', models.DateField()),
                ('FinalCode', models.CharField(max_length=8, unique=True)),
                ('sold_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
