# Generated by Django 4.2.10 on 2024-02-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_solditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloths',
            name='SIZE',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL'), ('6XL', '6XL')], default='S', max_length=3),
        ),
        migrations.AddField(
            model_name='solditem',
            name='SIZE',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2XL', '2XL'), ('3XL', '3XL'), ('4XL', '4XL'), ('5XL', '5XL'), ('6XL', '6XL')], default='S', max_length=3),
        ),
    ]
