# Generated by Django 4.2.10 on 2024-02-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Age',
            field=models.IntegerField(default=23),
        ),
    ]
