# Generated by Django 4.2.10 on 2024-02-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_customer_sold_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloths',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='solditem',
            name='Price',
        ),
        migrations.AlterField(
            model_name='cloths',
            name='MRP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='MRP',
            field=models.IntegerField(),
        ),
    ]
