# Generated by Django 4.2.10 on 2024-02-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_remove_cloths_price_remove_solditem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloths',
            name='FinalCode',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='FinalCode',
            field=models.CharField(max_length=8),
        ),
    ]
