# Generated by Django 4.2.10 on 2024-03-02 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_alter_customer_sold_on_alter_solditem_sold_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solditem',
            name='sold_on',
        ),
        migrations.AddField(
            model_name='solditem',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='first_app.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sold_on',
            field=models.DateField(),
        ),
    ]
