# Generated by Django 4.2.10 on 2024-03-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_remove_solditem_sold_on_solditem_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solditem',
            name='customer',
        ),
        migrations.AddField(
            model_name='solditem',
            name='sold_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
