# Generated by Django 4.2.10 on 2024-03-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_remove_solditem_customer_solditem_sold_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='solditem',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='first_app.customer'),
        ),
    ]
