# Generated by Django 4.2.10 on 2024-03-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_remove_solditem_customer_alter_customer_sold_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sold_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solditem',
            name='sold_on',
            field=models.DateField(),
        ),
    ]
