# Generated by Django 4.2.10 on 2024-03-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_alter_customer_sold_on_alter_solditem_sold_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='BillNo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='solditem',
            name='BillNo',
            field=models.IntegerField(default=1),
        ),
    ]
