# Generated by Django 4.2.10 on 2024-04-02 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0017_appuser_remove_accessrecord_name_delete_newusers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='BillNo',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sold_on',
        ),
        migrations.RemoveField(
            model_name='solditem',
            name='BillNo',
        ),
        migrations.AddField(
            model_name='solditem',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='first_app.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PhoneNumber',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
