# Generated by Django 4.2.10 on 2024-04-02 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0018_delete_appuser_remove_customer_billno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solditem',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.customer'),
        ),
    ]
