# Generated by Django 4.2.10 on 2024-04-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0019_alter_solditem_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='solditem',
            name='customer',
        ),
        migrations.AddField(
            model_name='solditem',
            name='BillNo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='solditem',
            name='PhoneNumber',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
