# Generated by Django 4.2.10 on 2024-04-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0020_appuser_remove_solditem_customer_solditem_billno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solditem',
            name='FinalCode',
            field=models.CharField(max_length=256),
        ),
    ]
